### ISSUE TITLE
Vis registrert, ikke-ferdig-konvertert video i listen hos arrangementet

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMvideo#19]
Vanskelig å vite om noe har gått galt eller om vi står i kø - og hvilke videoer som faktisk er lastet opp, når man skal lage mange.

Assigner deg for review / feedback på om denne bør være her @mariusmandal

**Comment by AsgeirSH** [comment]
(Gjelder hvert fall videoreportasjer)

**Comment by mariusmandal** [comment]
Hmm.. jeg trodde egentlig dette var på plass, men godt mulig jeg blander med bildekonverteringen (hvor jeg vet det er på plass). Skal uansett legge det til på todo'n, for det bør absolutt være der @AsgeirSH .

Ser vi har tabell- og kode-støtte på plass for å gjøre det, så må bare se på hvorfor det ikke er implementert. Tid kanskje?
https://github.com/UKMNorge/UKMapi/tree/master/Filmer#ukm_uploaded_video

https://github.com/UKMNorge/UKMapi/blob/master/Filmer/Upload/Queue.php#L39

Må uansett inn her på et vis, enten som en egen kolonne/boks, som en del av listen, eller i topp/bunn av listen.
https://github.com/UKMNorge/UKMvideo/blob/master/twig/home.html.twig

**Comment by AsgeirSH** [comment]
Lol, dette finnes, men jeg så det absolutt ikke - gikk litt for i ett med siden 😅 

![image](https://user-images.githubusercontent.com/1831028/101557089-8a307b00-39bc-11eb-98a0-495c7b6e3d2e.png)

**Comment by mariusmandal** [comment]
Endre farge på konverteringskø-boksen hvis den har filmer `alert-info` f.eks?
Legg også til en oppdater-knapp, som refresher siden

**Comment by mariusmandal** [comment]
## Løsningsforslag
**Tilnærming:** Programmering

Legg til `alert-info` på containeren, slik at boksen skiller seg ut fra de andre (Se bilde over)

## Gjenskape problemet
- Logg inn i arrangørsystemet
- Velg en kommune
- Velg et arrangement med påmeldte deltakere
- Velg "Filmer" i menyen (underlagt "nettside")
- Last opp en film

For at dette skal fungere må videoconverter og videostorage-VM kjøre på maskinen din.

**På UKM-mac:**
Å kjøre følgende kommando burde spinne opp de nødvendige VM'ene (i tillegg til main da):

```zsh 
dev; v up videoconverter; v up videostorage
```
