### ISSUE TITLE
Støtte for 50fps video 

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMvideo#20]
Vet det er liten vilje for å modde ffmpeg-skriptene - men får "Mangler videostørrelser"-feilen for store / 50fps-videofiler igjen.
![image](https://user-images.githubusercontent.com/1831028/101422339-baade180-38f6-11eb-941f-4b6090d00de0.png)

**Comment by mariusmandal** [comment]
@jardarn kan du se på hvorfor dette skjer?
Interessant å vite hvorvidt dette skjer pga stor filstørrelse/50fps. @AsgeirSH har du prøvd å laste opp liten fil med 50fps?

**Comment by AsgeirSH** [comment]
Hadde ikke noen liten 50fps-fil tilgjengelig - kan se om jeg får laget èn.

**Comment by mariusmandal** [comment]
@AsgeirSH, vet du by any chance om filen var større enn 2GB? 😬

**Comment by AsgeirSH** [comment]
Rimelig sikker på at den var større enn det, men under 4GB.

**Comment by jardarn** [comment]
2gb er maks siden vi ikke bruker chunked file upload. Jeg har manuelt lastet opp en fil som var større, og som var 50fps. Den gikk igjennom konverteren.

**Comment by mariusmandal** [comment]
Lukker denne, da feilen ligger i 2GB-grensen, som vi prøver å ta tak i på annen måte 😊
