### ISSUE TITLE
Oppdatering av embed-visning mangler trigger

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMvideo#4]
Når man i grovsorteringen i program-modulen endrer synlighet på en hendelse, har dette ingen hooks, og trigger derfor ikke oppdateringen av visningstider for embed-kode.
Ny hook må lages, og UKMvideo må lytte etter denne, likt som når en hendelse lagres

**Comment by AsgeirSH** [comment]
Så... ny do_action i UKMProgram/ajax/save/program.save.php.

add_action('UKMprogram_show', xx) i UKMvideo et sted? Finner ikke helt hvor/hvordan oppdateringen av visningstider gjøres.

**Comment by mariusmandal** [comment]
Jeg mener du kan legge til denne i lagringen


do_action('UKMpush_to_front_generate_object');





Som da vil trigge funksjoner i denne fila og regenerere visningsdata :)



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
Jepp, det er i hvert fall det Livestream-objektet gjør. Får ikke testa det lokalt av en eller annen grunn, men pusher likevel.

**Comment by AsgeirSH** [comment]
Mangler testing, ellers ok.
