### ISSUE TITLE
Bør inn under UKM-TV

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMvideo#5]
Se hook linje 26 i UKMvideo.php

**Comment by mariusmandal** [comment]
Gjelder vel kun network admin, @AsgeirSH ?

**Comment by AsgeirSH** [comment]
Ja, veldig enig i det, med mindre du vil markedsføre begrepet UKM-TV mer.

**Comment by mariusmandal** [comment]
Nei, for brukerne må det hete video, det er nok mer logisk :)



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox
