### ISSUE TITLE
Faner som undermenyer

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMvideo#6]
Det må være enklere å komme til last opp videoreportasje, alle faner bør derfor får egen undermeny-lenke:
- [ ] innslag
- [ ] videoreportasje
- [ ] last opp reportasje
- [ ] direktesending (hvis aktivert)

**Comment by AsgeirSH** [comment]
![skjermbilde 2016-02-25 kl 17 42 36](https://cloud.githubusercontent.com/assets/1831028/13326771/8687cc8e-dbe7-11e5-85fc-000926a769a2.png)
Jeg får ikke til å gjøre current page **bold**, den er stuck på opprinnelig side. Noen fiks, eller don't bother?

**Comment by mariusmandal** [comment]
Akkurat den der bør gjøres 100%, så da må de vel nesten registreres som subpages, og koden «splittes» litt mer?


Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
I fix (Y)
